### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by hapiman** [jackhutu/jackblog-react-redux#1]
follow your document, i can not  start the project.can u help?
![image](https://cloud.githubusercontent.com/assets/7567048/13658831/a843eb36-e6b5-11e5-88c9-bff24f3f537c.png)

**Comment by hutuxuhui** [comment]
What is the error message?Try the latest version.  fix #1

**Comment by hapiman** [comment]
i have solved it. Most probably,it's my fault,thks.
