### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by sinian1989** [jackhutu/jackblog-react-redux#10]
博主，请教个问题，最好能加下我QQ282798275，或者告诉我你的， 我现在是页面里有很多地方有window对象或者是有window.navigator.userAgent；这样node渲染时运行server.js的时候,serverRender报错，没有window对象，想问下这种怎么解决呢

**Comment by sinian1989** [comment]
一般用到window.navigator.userAgent的页面都是判断是不是微信或者APP之类的地方

**Comment by hutuxuhui** [comment]
打包方式和jackblog-react是相似的吗? webpack配置中可有target: "node"

**Comment by sinian1989** [comment]
恩 有 打包server的是复制你的

**Comment by sinian1989** [comment]
可不可以加下你QQ

**Comment by hutuxuhui** [comment]
已经加了.
