### ISSUE TITLE
再次渲染时，无法进行seo的问题

### ISSUE THREAD

**Issue by moxiaobei2** [jackhutu/jackblog-react-redux#11]
问题是这样的，文章列表初始化时，可进行渲染，并进行seo的，但是在加载 时，进行state的更改时，并不能进行再次的处理，seo不到新加载的内容，这个怎么破？？

**Comment by hutuxuhui** [comment]
这没有关系, 首屏加载后, 就交给前端了, 但是你在其它页面单独刷新时也是走的服务端渲染.

**Comment by moxiaobei2** [comment]
不是哦，我意思是比如一个分页，加载的时候有一层数据，更多的时候，前端会加载更多的数据，但是在查看源码时又没有加载更多时的那些数据哦，这样爬不到更多里面的内容。

**Comment by hutuxuhui** [comment]
嗯, 你说的是对的, 但是貌似没有什么好办法.
