### ISSUE TITLE
关于bindActionCreators的优化

### ISSUE THREAD

**Issue by hiddaorear** [jackhutu/jackblog-react-redux#12]
看着这个项目学react的，做的过程中发现，可以把bindActionCreators这一步移动到actions的index.js文件中，这样可以一次性统一bindActionCreators。这样做会有弊端吗？

**Comment by hutuxuhui** [comment]
你可以大胆的尝试,  其实这些东西本身就在快速变化中, 就是坑. 想弄清楚这里面的秘密, 还是要研究的很深才行.

**Comment by hiddaorear** [comment]
哈哈，正在看redux的源码。正在做一个react+redux项目的优化，问这个问题是出于项目工程角度。谢谢你！
