### ISSUE TITLE
@connect(mapStateToProps,mapDispatchToProps)这样的装饰器语法是需要加什么插件吗？

### ISSUE THREAD

**Issue by xgzl87** [jackhutu/jackblog-react-redux#15]
@connect(mapStateToProps,mapDispatchToProps)

**Comment by hutuxuhui** [comment]
这是es7语法,  需要配置好babel插件. 可以看一下项目里 .babelrc文件.

**Comment by xgzl87** [comment]
谢谢啊，有没有对应babel配置资料啊？麻烦共享一下可以吧

**Comment by hutuxuhui** [comment]
babel官网上都有很详细的文档, http://babeljs.io/docs/plugins/transform-decorators  你可以看看.
