### ISSUE TITLE
关于服务端渲染，路由页面子组件内的数据预获取问题

### ISSUE THREAD

**Issue by neroneroffy** [jackhutu/jackblog-react-redux#16]
看到您的这个项目做了服务端数据的预获取，那么路由页面的子组件的数据看到您是在路由页面发的请求获取的，也就是说服务端的时候父组件代替子组件发请求获取数据。那这样做是不是有违组件低耦合的原则呢？我没接触过正式的SSR项目，不清楚一般这种问题是怎么解决的，所以来请教一下

**Comment by hutuxuhui** [comment]
@neroneroffy  初始数据的获取放在容器组件这也是常用作法,  当然如果你放在子组件, 那只要你有办法让服务端拿到你请求数据的这个动作, 并触发, 也是没问题的.

**Comment by neroneroffy** [comment]
@jackhutu 感谢您回答，我自己曾经对这种情况做了处理。
