### ISSUE TITLE
npm run dev 启动错误

### ISSUE THREAD

**Issue by huanghaiyang** [jackhutu/jackblog-react-redux#2]
win10平台，nodejs4.1.1,npm2.14.4，启动报错如下：

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart jackblog-react-redux@2.1.0
6 info start jackblog-react-redux@2.1.0
7 verbose unsafe-perm in lifecycle true
8 info jackblog-react-redux@2.1.0 Failed to exec start script
9 verbose stack Error: jackblog-react-redux@2.1.0 start: `npm-run-all --sequential build start-prod`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid jackblog-react-redux@2.1.0
11 verbose cwd C:\Users\haiyang\github\jackblog-react-redux
12 error Windows_NT 10.0.10586
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
14 error node v4.1.1
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error jackblog-react-redux@2.1.0 start: `npm-run-all --sequential build start-prod`
17 error Exit status 1
18 error Failed at the jackblog-react-redux@2.1.0 start script 'npm-run-all --sequential build start-prod'.
18 error This is most likely a problem with the jackblog-react-redux package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm-run-all --sequential build start-prod
18 error You can get their info via:
18 error     npm owner ls jackblog-react-redux
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by hutuxuhui** [comment]
安装包都正常安装了吗?  分别运行以下两个命令试试看: 

```
webpack --colors --config ./webpack/webpack.config.dev.server.js
set NODE_ENV=development && nodemon server.js
```

我的运行环境: mac, node 4.4.0 ,  npm 2.14.20 可以正常启动, 没有错误.  
windowns 环境我没有试过. npm-run-all 和 better-npm-run 这两个包据介绍都兼容windows
