### ISSUE TITLE
npm run dev fail

### ISSUE THREAD

**Issue by yuanzougaofei97** [jackhutu/jackblog-react-redux#4]
0 info it worked if it ends with ok
1 verbose cli [ '/var/lib/nodejs/node-v4.4.2-linux-x64/bin/node',
1 verbose cli   '/var/lib/nodejs/node-v4.4.2-linux-x64/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev jackblog-react-redux@2.1.0
6 info dev jackblog-react-redux@2.1.0
7 verbose unsafe-perm in lifecycle true
8 info jackblog-react-redux@2.1.0 Failed to exec dev script
9 verbose stack Error: jackblog-react-redux@2.1.0 dev: `npm-run-all --sequential build-server:dev start-dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/var/lib/nodejs/node-v4.4.2-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/var/lib/nodejs/node-v4.4.2-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid jackblog-react-redux@2.1.0
11 verbose cwd /var/lib/nodejs/jackblog-react-redux-master
12 error Linux 3.10.0-229.el7.x86_64
13 error argv "/var/lib/nodejs/node-v4.4.2-linux-x64/bin/node" "/var/lib/nodejs/node-v4.4.2-linux-x64/bin/npm" "run" "dev"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error jackblog-react-redux@2.1.0 dev: `npm-run-all --sequential build-server:dev start-dev`
17 error Exit status 1
18 error Failed at the jackblog-react-redux@2.1.0 dev script 'npm-run-all --sequential build-server:dev start-dev'.
18 error This is most likely a problem with the jackblog-react-redux package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm-run-all --sequential build-server:dev start-dev
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs jackblog-react-redux
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls jackblog-react-redux
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by hutuxuhui** [comment]
没问题了吗?

**Comment by yuanzougaofei97** [comment]
npm install 可以了， npm start 不行。

**Comment by yuanzougaofei97** [comment]
运行 npm run dev 详细的日志

控制台输出：

> jackblog-react-redux@2.1.0 dev /var/lib/nodejs/jackblog-react-redux-master
> npm-run-all --sequential build-server:dev start-dev
> 
> jackblog-react-redux@2.1.0 build-server:dev /var/lib/nodejs/jackblog-react-redux-master
> better-npm-run build-dev-server

running better-npm-run in /var/lib/nodejs/jackblog-react-redux-master
Executing script: build-dev-server

to be executed: webpack --colors --config ./webpack/webpack.config.dev.server.js 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)

npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/var/lib/nodejs/node-v4.4.2-linux-x64/bin/node" "/var/lib/nodejs/node-v4.4.2-linux-x64/bin/npm" "run-script" "build-server:dev"
npm ERR! node v4.4.2
npm ERR! npm v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! jackblog-react-redux@2.1.0 dev: npm-run-all --sequential build-server:dev start-dev
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jackblog-react-redux@2.1.0 dev script 'npm-run-all --sequential build-server:dev start-dev'.
npm ERR! This is most likely a problem with the jackblog-react-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm-run-all --sequential build-server:dev start-dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs jackblog-react-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR! npm owner ls jackblog-react-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /var/lib/nodejs/jackblog-react-redux-master/npm-debug.log

日志输出：

0 info it worked if it ends with ok
1 verbose cli [ '/var/lib/nodejs/node-v4.4.2-linux-x64/bin/node',
1 verbose cli '/var/lib/nodejs/node-v4.4.2-linux-x64/bin/npm',
1 verbose cli 'run',
1 verbose cli 'dev' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev jackblog-react-redux@2.1.0
6 info dev jackblog-react-redux@2.1.0
7 verbose unsafe-perm in lifecycle true
8 info jackblog-react-redux@2.1.0 Failed to exec dev script
9 verbose stack Error: jackblog-react-redux@2.1.0 dev: npm-run-all --sequential build-server:dev start-dev
9 verbose stack Exit status 1
9 verbose stack at EventEmitter. (/var/lib/nodejs/node-v4.4.2-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack at emitTwo (events.js:87:13)
9 verbose stack at EventEmitter.emit (events.js:172:7)
9 verbose stack at ChildProcess. (/var/lib/nodejs/node-v4.4.2-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack at emitTwo (events.js:87:13)
9 verbose stack at ChildProcess.emit (events.js:172:7)
9 verbose stack at maybeClose (internal/child_process.js:827:16)
9 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid jackblog-react-redux@2.1.0
11 verbose cwd /var/lib/nodejs/jackblog-react-redux-master
12 error Linux 3.10.0-229.el7.x86_64
13 error argv "/var/lib/nodejs/node-v4.4.2-linux-x64/bin/node" "/var/lib/nodejs/node-v4.4.2-linux-x64/bin/npm" "run" "dev"
14 error node v4.4.2
15 error npm v2.15.0
16 error code ELIFECYCLE
17 error jackblog-react-redux@2.1.0 dev: npm-run-all --sequential build-server:dev start-dev
17 error Exit status 1
18 error Failed at the jackblog-react-redux@2.1.0 dev script 'npm-run-all --sequential build-server:dev start-dev'.
18 error This is most likely a problem with the jackblog-react-redux package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error npm-run-all --sequential build-server:dev start-dev
18 error You can get information on how to open an issue for this project with:
18 error npm bugs jackblog-react-redux
18 error Or if that isn't available, you can get their info via:
18 error
18 error npm owner ls jackblog-react-redux
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by hutuxuhui** [comment]
是什么系统? 感觉应该删除node_modules , 重新npm install

**Comment by yuanzougaofei97** [comment]
## 系统：

Linux 3.10.0-229.el7.x86_64
node v4.4.2
npm v2.15.0

## 我觉得应该是这块的问题：

Error: write EPIPE
at exports._errnoException (util.js:870:11)
at WriteWrap.afterWrite (net.js:769:14)

**Comment by hutuxuhui** [comment]
刚刚在linux系统上试了一下, 确实有个问题, 文件路径大小写问题, 我已经修复, 但是像你说的问题我没有遇到, 你可以再下载试试, 我的测试环境: 
Ubuntu 12.04 LTS x86_64
node v4.4.2
npm v2.15.0

**Comment by yuanzougaofei97** [comment]
大小写问题现在解决了，现在就运行 npm run dev , 剩下这个问题

ERROR in ./src/assets/images/tiny.gif
Module build failed: Error: spawn /var/lib/nodejs/test/redux5/jackblog-react-redux-master/node_modules/image-webpack-loader/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
 @ ./src/components/Home/tags.js 16:12-51

**Comment by hutuxuhui** [comment]
你这应该是image-webpack-loader这包没起作用, 重装一下试试, 否则处理不了图片.

**Comment by yuanzougaofei97** [comment]
重装了还是不行，我的系统是centos7.1 

npm install的时候出现会出现如下信息

## 如下

npm WARN optional dep failed, continuing fsevents@1.0.12
npm WARN optional dep failed, continuing fsevents@1.0.12
npm WARN optional dep failed, continuing fsevents@1.0.12

> pngquant-bin@3.1.0 postinstall /var/lib/nodejs/test/redux7/jackblog-react-redux-master/node_modules/image-webpack-loader/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  鈿[39m The `/var/lib/nodejs/test/redux7/jackblog-react-redux-master/node_modules/image-webpack-loader/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  鈿[39m pngquant pre-build test failed
  鈩[39m compiling from source
  鉁[39m pngquant built successfully
npm WARN cannot run in wd gifsicle@3.0.3 node lib/install.js (wd=/var/lib/nodejs/test/redux7/jackblog-react-redux-master/node_modules/image-webpack-loader/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle)

> jpegtran-bin@3.0.6 postinstall /var/lib/nodejs/test/redux7/jackblog-react-redux-master/node_modules/image-webpack-loader/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  鉁[39m jpegtran pre-build test passed successfully

> optipng-bin@3.1.1 postinstall /var/lib/nodejs/test/redux7/jackblog-react-redux-master/node_modules/image-webpack-loader/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  鉁[39m optipng pre-build test passed successfully

**Comment by yuanzougaofei97** [comment]
请问是否需要安装 gifsicle命令行？你环境中有这个命令吗？

**Comment by hutuxuhui** [comment]
我的环境没有这个命令, 估计你的系统缺少图片处理的必要库, 装一下`yum install libpng-devel` 这个, 再试试.

**Comment by yuanzougaofei97** [comment]
我使用的是centos7 mini版  ， 前面安装过程中，确实出现了一些问题，通过安装这个包：libpng-devel-1.5.13-7.el7_2.x86_64解决了。
但是目前这个问题还是存在。

**Comment by hutuxuhui** [comment]
不如换个系统吧, 时间就是生命, 要珍爱生命.

**Comment by yuanzougaofei97** [comment]
好的，我试试，谢谢。

**Comment by SidFeng** [comment]
@yuanzougaofei97 你解决了吗？我也遇到同样的问题，windows10下，跑不起来
`$ webpack --colors --config ./webpack/webpack.config.dev.server.js
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:856:11)
    at Socket._writeGeneric (net.js:679:26)
    at Socket._write (net.js:698:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Socket.Writable.write (_stream_writable.js:215:11)
    at Socket.write (net.js:624:40)
    at Socket.Writable.end (_stream_writable.js:443:10)
    at Socket.end (net.js:406:31)`

**Comment by yuanzougaofei97** [comment]
你环境搭建好了吗，如果没有，你先把环境搭建好吧，参考 https://github.com/nodejs/node-gyp 。 我win10 搭建好环境后，没出现什么问题了。

**Comment by SidFeng** [comment]
@yuanzougaofei97 谢谢，原来是没翻墙，少装了很多依赖的包，目前已经解决了
