### ISSUE TITLE
能写个blog介绍下vue2，ng2和react这三种实现的优缺点吗

### ISSUE THREAD

**Issue by leedstyh** [jackhutu/jackblog-react-redux#6]
目前正在学习react的同构，也对另外2个感兴趣

**Comment by hutuxuhui** [comment]
vue2和ng2的同构我目前也还没有尝试,  vu2和ng2目前还没有出正式版, 特别是ng2总是变来变去. 
至于优点, react: 成熟, vue:轻, ng2:概念新

**Comment by leedstyh** [comment]
哦我以为其他两个也做了同构呢，谢谢啦
