### ISSUE TITLE
开发环境client和server代码不一致

### ISSUE THREAD

**Issue by troywith77** [jackhutu/jackblog-react-redux#9]
使用npm run dev开发的时候如果修改了代码clent会自动更新，但是如果刷新的话会提示服务器渲染的代码和客户端不一致，要结束进程重新npm run dev才行，不知道作者是怎么解决这个问题的？

**Comment by hutuxuhui** [comment]
确实有这个问题, 修改代码后client有热替换, 但是即使将server端代码也重新编译,还是有这个警告.  
 我在package.json文件 增加build-server:watch项, 监控server端代码. 同时用两个命令行窗口, 一个运行npm run build-server:watch, 别一个运行npm run start-dev, 这时只要改变代码, 原则上来讲都一样了.
